name: Black Formatter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  black:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          make format
