name: Test

on:
  workflow_run:
    workflows: ["ruff"]
    branches: ["main"]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install build dependencies
    - run: |
        sudo apt-get install -y build-essential gcc
    - run: |
        pip install --prefer-binary -r requirements.txt
    - run: |
        make lint
