name: Test

on:
  workflow_run:
    workflows: ["Lint"]
    branches: ["main"]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
          pip install ruff
    - run: |
          pip install nbqa
    - run: |
        make test
